Plataforma/PrimerosPasos/src/plataforma1/app_prueba/urls.py
from django.urls import path
from app_prueba import views
from .apiviews import AlbumAPI

app_name="app_prueba"

urlpatterns = [
    path('info_cacao', views.info_cacao, name="info-cacao"), #actividad 3
    path('info_cacao2', views.info_cacao_form, name="info-cacao2"), #actividad 4
    path('cargar-video', views.showvideo, name="mostrar-video"), #actividad 8

    path('control-manual', views.control_manual, name="control-manual"), #actividad 6
    path('album-imagenes', AlbumAPI.as_view()), #actividad 6
]

Plataforma/PrimerosPasos/src/plataforma1/plataforma1/urls.py
from django.contrib import admin
from django.urls import path, include
from app_prueba import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index1),
    path('app_prueba/', include('app_prueba.urls', namespace="app_prueba")),
    path('piscicultura/', include('piscicultura.urls', namespace="piscicultura")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Plataforma/PrimerosPasos/src/plataforma1/app_prueba/models.py
from django.db import models

# Create your models here.
class Estudiantes(models.Model):
    nombre = models.CharField(max_length=50)
    cedula = models.IntegerField()

    def __str__(self):
        return self.nombre

class ProduccionCacao(models.Model):
    cod_dep = models.IntegerField()
    departamento = models.CharField(max_length=50)
    cod_mun = models.IntegerField()
    municipio = models.CharField(max_length=50)
    grupo_cultivo = models.CharField(max_length=50)
    sub_grupo_cultivo = models.CharField(max_length=50)
    cultivo = models.CharField(max_length=50)
    sistema_productivo = models.CharField(max_length=50)
    codigo_cultivo = models.IntegerField()
    nombre_cientifico = models.CharField(max_length=50)
    periodo = models.IntegerField()
    area_sembrada = models.FloatField() #ha
    area_cosechada = models.FloatField() #ha
    produccion = models.FloatField() # ton
    rendimiento = models.FloatField() #ton/ha
    estado_produccion = models.CharField(max_length=50)


    def __str__(self):
        return self.municipio+" "+ str(self.produccion)+ "ton"

class Departamentos(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Produccion_municipios(models.Model):
    departamento = models.ForeignKey(Departamentos, on_delete=models.CASCADE)
    cod_municipio = models.IntegerField()
    municipio = models.CharField(max_length=50)
    cultivo = models.CharField(max_length=50)
    codigo_cultivo = models.IntegerField()
    nombre_cientifico = models.CharField(max_length=50)
    periodo = models.IntegerField()
    area_sembrada = models.FloatField()
    area_cosechada = models.FloatField()
    produccion = models.FloatField()
    rendimiento = models.FloatField()
    estado_produccion = models.CharField(max_length=50)

    def __str__(self):
        return self.municipio


class AlbumImagenes(models.Model):
    """ esta tabla se encarga de registrar todas las imagenes del cielo tomadas """
    imagen = models.ImageField(upload_to='album/imagenes', height_field=None, width_field=None, max_length=None)
    fecha = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __unicode__(self):
        return self.imagen

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'AlbumImagenes'
        verbose_name_plural = 'AlbumImageness'

class Video(models.Model):
    name = models.CharField(max_length=50)
    videofile = models.FileField(upload_to='videos/', null = True, max_length=100, verbose_name="")

    def __str__(self):
        return self.name +" : "+ str(self.videofile)

Plataforma/PrimerosPasos/src/plataforma1/app_prueba/forms.py
from django import forms
from .models import Produccion_municipios
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ("name", "videofile")

class DepartamentosForm(forms.Form):
    departamento = forms.CharField(max_length=50)

class Produccion_municipiosForm(forms.ModelForm):
    class Meta:
        model = Produccion_municipios
        fields = ('departamento',)


Plataforma/PrimerosPasos/src/plataforma1/app_prueba/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Estudiantes, ProduccionCacao, Produccion_municipios, AlbumImagenes, Video
from .forms import DepartamentosForm, Produccion_municipiosForm, VideoForm


def showvideo(request):
    try:
        lastvideo = Video.objects.last()
        videofile = lastvideo.videofile
        if request.POST:
            form = VideoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
        context = {"videofile": videofile, "form": form}
    except:
        form = VideoForm()
        context = {"form": form}
        if request.POST:
            form = VideoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return render(request, "app_prueba/videos.html", context)
    return render(request, "app_prueba/videos.html", context)

# Create your views here.
def index(request):
    integrantes = Estudiantes.objects.all()
    integrantes = integrantes.values("nombre", "cedula")
    print(integrantes)
    return HttpResponse(integrantes)

def index1(request):
    return render(request, "app_prueba/index.html")

def info_cacao(request):
    departamento = "SANTANDER"
    cacao = ProduccionCacao.objects.filter(departamento=departamento).order_by("municipio")
    cacao = cacao.values("area_sembrada", "area_cosechada", "produccion", "rendimiento", "municipio")
    total_area = 0
    total_produccion = 0
    for dat in cacao:
        total_area=total_area+dat["area_sembrada"]
        total_produccion  = total_produccion + dat["produccion"]

    respuesta = {"cacao": cacao, "area_total": total_area,
                "total_produccion": total_produccion, 
                "departamento": departamento,}

    return render(request, "app_prueba/info_cacao.html", respuesta)

def info_cacao_form(request):
    form_dep = Produccion_municipiosForm()
    if request.POST:
        print(request.POST)
        cacao = Produccion_municipios.objects.filter(departamento_id = request.POST["departamento"]).order_by("municipio")
        cacao = cacao.values("area_sembrada", "area_cosechada", "produccion", "rendimiento", "municipio")
        respuesta = {"cacao": cacao,"form_dep": form_dep}
    else:
        respuesta = {"form_dep": form_dep}
    return render(request, "app_prueba/info_cacao2.html", respuesta)
    

def control_manual(request):
    album = AlbumImagenes.objects.all()
    respuesta = {"imagenes": album,}
                
    return render(request, "app_prueba/control_manual.html", respuesta)

Plataforma/PrimerosPasos/src/plataforma1/templates/app_prueba/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>plataforma</title>
</head>
<body>
 
{% block body_block %}

{% endblock  %}

</body>
</html>

Plataforma/PrimerosPasos/src/plataforma1/templates/app_prueba/control_manual.html
{% extends 'app_prueba/base1.html' %}

{% block body_block %}

<div class="container">
<div class="jumbotron">
<h1> Colección de Imágenes almacenadas en la base de datos </h1>
</div>
{% for data in imagenes %}
<img src="{{ data.imagen.url }}" alt="no encontrado" class="img-thumbnail" height="200px" width="300px">
{% endfor %}
</div>
{% endblock  %}


Plataforma/PrimerosPasos/src/plataforma1/templates/app_prueba/index.html
{% extends 'app_prueba/base1.html' %}

{% block body_block %}

<div class="container">
<h1> Bienvenidos a la capacitacion plataforma </h1>
<h2> Actividades </h2>
 <ol>
  <li><a href="{% url 'app_prueba:info-cacao' %}">Actividad 3 </a></li>
  <li><a href="{% url 'app_prueba:info-cacao2' %}">Actividad 4 </a></li>
  <li><a href="{% url 'app_prueba:info-cacao' %}">Actividad 5 </a></li>
</ol> 

</div>

{% endblock  %}

Plataforma/PrimerosPasos/src/plataforma1/templates/app_prueba/info_cacao.html
{% extends 'app_prueba/base1.html' %}

{% block body_block %}

 <div class="container">
 <div class="jumbotron">
<h1> Datos plataforma </h1>
<h3> Area total sembrada en {{departamento}} {{area_total}} ha
<h3> Produccion total en {{departamento}} {{total_produccion}} ton
 </div>

 <table class="table">
  <thead>
    <tr>
      <th scope="col">Area sembrada ha</th>
      <th scope="col">Area cosechada ha</th>
      <th scope="col">Produccion ton</th>
      <th scope="col">Rendimiento ton/ha</th>
      <th scope="col">Municipio</th>

    </tr>
  </thead>
  <tbody>
  {% for dato in cacao %}
        <tr>
      <th scope="row">{{dato.area_sembrada}}</th>
      <td>{{dato.area_cosechada}} </td>
      <td>{{dato.produccion}} </td>
      <td>{{dato.rendimiento}} </td>
            <td>{{dato.municipio}} </td>

        </tr>
  {% endfor %}

    
  </tbody>
</table>
 </div>
{% endblock  %}

Plataforma/PrimerosPasos/src/plataforma1/templates/app_prueba/info_cacao2.html
{% extends 'app_prueba/base1.html' %}
{% block body_block %}

<h1> Información del cacao </h1>

<form action="{% url 'app_prueba:info-cacao2'%}" method="post">
    {% csrf_token %}
    {{form_dep}}
    <input type="submit" value="filtrar">
</form>
<div class="row">
    <div class="col">

        <table class="table">
            <thead>
              <tr>
                <th scope="col">Area sembrada ha</th>
                <th scope="col">Area cosechada ha</th>
                <th scope="col">Produccion ton</th>
                <th scope="col">Rendimiento ton/ha</th>
                <th scope="col">Municipio</th>
          
              </tr>
            </thead>
            <tbody>
            {% for dato in cacao %}
                  <tr>
                <th scope="row">{{dato.area_sembrada}}</th>
                <td>{{dato.area_cosechada}} </td>
                <td>{{dato.produccion}} </td>
                <td>{{dato.rendimiento}} </td>
                      <td>{{dato.municipio}} </td>
          
                  </tr>
            {% endfor %}
          
              
            </tbody>
          </table>
    </div>
    <div class="col"></div>
</div>
{% endblock  %}

Plataforma/PrimerosPasos/src/plataforma1/templates/app_prueba/videos.html
{% extends 'app_prueba/base1.html' %}

{% block body_block %}
<div class="container">

<h1>Video subido</h1>
<form enctype="multipart/form-data" action="{% url 'app_prueba:mostrar-video' %}" method="post" accept="video/mp4"
target="_blank">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Subir video">
</form>

<video width="500" controls>
<source src="{{ videofile.url }}" type="video/mp4" > </source>
Su navegador no soporta este video
</video>
</div>

{% endblock  %}